# Generated by Django 3.0.3 on 2020-03-28 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200328_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('capacitie', models.IntegerField(blank=True, null=True)),
                ('working', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('capacitie', models.IntegerField(blank=True, null=True)),
                ('working', models.BooleanField(default=True)),
                ('Generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Generator')),
            ],
        ),
    ]
